export const LANG = {
	EN: {
		appDesc: "DApp Builder",
		from: "from",
		my: "My",
		mys: "My",
		liquidity: "Liquidity",
		liquiditys: "Liquidity",
		manage: "Manage",
		to: "to",
		or: "Or",
		add: "Add",
		buy: "Buy",
		buybuy: "Buy",
		buyTicket: "Buy Ticket",
		myTicket: "My Ticket",
		lastTicketBought: "Last Ticket Sold",
		roundInfo: "Prize Info",
		walletInfo: "Wallet Data",
		confirmation: "Confirmation",
		myAccount: "My Account",
		tx: "Transaction",
		sell: "Sell",
		approve: "Accept TOS",
		disapprove: "Forget TOS",
		remove: "Remove",
		trade: "Trade",
		amount: "Amount",
		for: "for",
		click: "Click",
		settings: "Settings",
		advanced: "Advanced",
		confirm: "Confirm",
		clear: "Clear",
		currentRound: "Current Round",
		redeem: "Redeem",
		refresh: "Refresh",
		weight: "Weight",
		farms: "Commission Farms",
		markets: "Markets",
		rates: "Exchange Rates",
		investedLps: "Invested LPs",
		comingSoon: "Coming Soon",
		farmLevel: "Farm Level",
		welcome: "Welcome",
		signup: "Sign Up",
		prizePool: "Prize Pool",
	
		connect: "Enter",
		wallet: "",
		seeMore: "See More",
		loading: "Loading",

		exchange: "Bureau de Change",
		myDashboard: "My Dashboard",
		slippage: "Margin of Error",
		availFarms: "Available Farms",
		savingsComissions: "Savigns Comissions",
		allocation: "Allocation",
		rewards: "Rewards",
		totalRewards: "Total Rewards",

		refreshBalance: "to refresh your balances",
		connectToContinue: "Connect your wallet to Continue",
		connectedAddress: "Connected Address",

		amenu_txs: "Transaction History",
		amenu_rules: "Rules of the game",
		amenu_contactUs: "Contact Us",

		help_calculator: "Click the calculator to get exchange rate",
		help_inputAmount: "Enter how much you want to trade",
		lastRewardBlock: "Last Rewarded Block",
		farmStats: "Farm Stats",
		switchTo: "Switch to",		
	},
	ES: {
		appDesc: "DApp Builder",
		from: "vender",
		my: "Mi",
		mys: "Mis",
		liquidity: "Cupón",
		liquiditys: "Cupones",
		manage: "Gestionar",
		to: "recibir",
		or: "O",
		trade: "Vender",
		amount: "Cantidad",
		for: "por",
		add: "Añadir",
		buy: "Comprar",
		buybuy: "Comprar",
		buyTicket: "Comprar Ticket",
		myTicket: "Mi Ticket",
		lastTicketBought: "Ultimo Ticket Vendido",
		roundInfo: "Info. de Sorteo",
		walletInfo: "Info. de Wallet",
		confirmation: "Confirmacion",
		myAccount: "Mi Cuenta",
		tx: "Transaccion",
		sell: "Vender",
		approve: "Firmar",
		disapprove: "Anular Firma",
		remove: "Quitar",
		click: "Clickea",
		settings: "Configuración",
		advanced: "Avanzado",
		confirm: "Confirmar",
		clear: "Limpiar",
		currentRound: "Sorteo Corriente",
		redeem: "Reclamar",
		refresh: "Refrescar",
		weight: "Peso",
		farms: "Granjas de Comisión",
		markets: "Mercados",
		rates: "Tasas de Cambio",
		investedLps: "Cupones Invertidos",
		comingSoon: "Próximamente",
		farmLevel: "Nivel de Fertilidad",
		welcome: "Bienvenido",
		signup: "Registrate",
		prizePool: "Premio Total",
	
		connect: "Entrar",
		wallet: "",
		seeMore: "Ver Mas",
		loading: "Cargando",

		exchange: "Casa de Cambio",
		myDashboard: "Mi Tablero",
		slippage: "Margen de Error",
		availFarms: "Granjas Disponibles",
		savingsComissions: "Comisión por Ahorro",
		allocation: "Asignación",
		rewards: "Recompensas",
		totalRewards: "Recompensas Totales",

		refreshBalance: "para refrescar tu saldo",
		connectToContinue: "Conecta tu cartera para Continuar",
		connectedAddress: "Mi Cuenta",

		amenu_txs: "Historial de Transacciones",
		amenu_rules: "Reglas de Juego",
		amenu_contactUs: "Contactanos",

		help_calculator: "Clickea la calculadora para generar precio",
		help_inputAmount: "Ingresa la cantidad a cambiar",
		lastRewardBlock: "Ultimo Lote Recompensado",
		farmStats: "Estadisticas de Granja",
		switchTo: "Cambiar a",		
	},
};